### ISSUE TITLE
cf push cf-subway error

### ISSUE THREAD

**Issue by bingo65334** [cloudfoundry-community/cf-subway#14]
main.go:7:2: cannot find package "github.com/cloudfoundry-community/cf-subway/broker" in any of:
	/tmp/tmp.uh3JhRQzv4/.go/src/cf-subway/vendor/github.com/cloudfoundry-community/cf-subway/broker (vendor tree)
	/tmp/cache/go1.7.5/go/src/github.com/cloudfoundry-community/cf-subway/broker (from $GOROOT)
	/tmp/tmp.uh3JhRQzv4/.go/src/github.com/cloudfoundry-community/cf-subway/broker (from $GOPATH)

**Comment by drnic** [comment]
Sorry about that. I'll investigate next week.
