### ISSUE TITLE
Subway is setting plan_updateable false when its true at service config 

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry-community/cf-subway#7]
@drnic 
Subway is setting plan_updatable false when its true at service level 

v2/catalog from Subway 
{"services":[{"id":"490b1c10-3a3f-420f-8516-xxxxx","name":"logstash","description":"Data pipeline to process logsl and event data.  Elasticsearch, Logstash, Kibana by Elastic","bindable":true,"tags":["logstash14","logstash","syslog"],"metadata":{},"requires":["syslog_drain"],"**plan_updateable":false**,"plans":[{"id":"xxxx-41da-4fb6-b2d8-624eb45b4c68","name":"free","description":"Free Trial","metadata":{"bullets":["Dedicated Logstash 1.4 server","Logstash 1.4 running inside a Docker container"],"costs":[{"amount":{"usd":0},"unit":"MONTHLY"}]},"free":true}]}]}

v2/catalog from actual backend node 
{"services":[{"id":"490b1c10-3a3f-420f-8516-xxx","name":"logstash","description":"Data pipeline to process logsl and event data.  Elasticsearch, Logstash, Kibana by Elastic","bindable":true,"tags":["logstash14","logstash","syslog"],"metadata":{"displayName":"Logstash 1.4","documentationUrl":"http://docs.run.pivotal.io","imageUrl":"data:image/png;base64,iVBO,"longDescription":"A Logstash 1.4 service for development and testing running inside a Docker container","providerDisplayName":"Pivotal Software","supportUrl":"http://support.run.pivotal.io/home"},"requires":["syslog_drain"],"plans":[{"id":"bce48f33-41da-4fb6-b2d8-xxx","name":"free","description":"Free Trial","metadata":{"bullets":["Dedicated Logstash 1.4 server","Logstash 1.4 running inside a Docker container"],"costs":[{"amount":{"usd":0},"unit":"MONTHLY"}]},"free":true}],"**plan_updateable":true**,"dashboard_client":{"id":"p-logstash-client","redirect_uri":"https://xxxx/manage/auth/cloudfoundry/callback","secret":"p-logstas

**Comment by amulyas** [comment]
@frodenas it can be issue with brokerapi which subway is using I am not sure though

**Comment by drnic** [comment]
Remove the underscore from your config file: try planupdateable: true

```
_____________________________
```

**Comment by amulyas** [comment]
@drnic no luck with planupdateable still the same

**Comment by amulyas** [comment]
@drnic any more suggestion here

**Comment by amulyas** [comment]
@drnic any suggestions?

**Comment by drnic** [comment]
@amulyas I believe is now resolved; and shipped in https://github.com/cloudfoundry-community/cf-subway-boshrelease/releases/tag/v3.2.0

The issue was that I was accidentally unmarshaling the inbound JSON (from backend /v2/catalog) as YAML. This worked enough that it wasn't a simple error to spot.

Looking at a broker /v2/catalog result I can now see `"plan_updateable":true`. Hurray.

**Comment by bingo65334** [comment]
@amulyas
which version of cf-subway do you use？ boshrelease or cf-subway app?
